--
-- PostgreSQL database dump
--

\restrict 456oVZLgTTjK4fuFcDAYCN5oZhX9IVEvg0iFaaQGbehulAVjxfi5U0TALYpsacL

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS railway;
--
-- Name: railway; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE railway WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE railway OWNER TO postgres;

\unrestrict 456oVZLgTTjK4fuFcDAYCN5oZhX9IVEvg0iFaaQGbehulAVjxfi5U0TALYpsacL
\connect railway
\restrict 456oVZLgTTjK4fuFcDAYCN5oZhX9IVEvg0iFaaQGbehulAVjxfi5U0TALYpsacL

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity_log (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    duration_seconds integer,
    status character varying(255),
    user_id bigint,
    workout_id bigint,
    feedback character varying(255)
);


ALTER TABLE public.activity_log OWNER TO postgres;

--
-- Name: activity_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activity_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    comment character varying(500),
    created_at timestamp(6) without time zone,
    rating integer,
    user_id bigint,
    workout_id bigint,
    activity_log_id bigint,
    difficulty character varying(255),
    liked boolean,
    CONSTRAINT feedback_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['TOO_EASY'::character varying, 'JUST_RIGHT'::character varying, 'TOO_HARD'::character varying])::text[])))
);


ALTER TABLE public.feedback OWNER TO postgres;

--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO postgres;

--
-- Name: greeting_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.greeting_message (
    id bigint NOT NULL,
    message character varying(255) NOT NULL
);


ALTER TABLE public.greeting_message OWNER TO postgres;

--
-- Name: greeting_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.greeting_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.greeting_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trainers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainers (
    id bigint NOT NULL,
    intro character varying(255),
    language character varying(255),
    name character varying(255),
    prompt character varying(255),
    voice character varying(255),
    image_select character varying(255),
    image_call character varying(255),
    image_start character varying(255),
    ambience character varying(255)
);


ALTER TABLE public.trainers OWNER TO postgres;

--
-- Name: trainers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trainers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trainers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_workout_preferences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_workout_preferences (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    preference_type character varying(255),
    user_id bigint,
    workout_id bigint,
    CONSTRAINT user_workout_preferences_preference_type_check CHECK (((preference_type)::text = ANY ((ARRAY['DISLIKED'::character varying, 'FAVORITE'::character varying])::text[])))
);


ALTER TABLE public.user_workout_preferences OWNER TO postgres;

--
-- Name: user_workout_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_workout_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_workout_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    clerk_id character varying(255) NOT NULL,
    context character varying(255),
    intensity_level integer,
    name character varying(255),
    role character varying(255),
    trainer_id bigint DEFAULT 1
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workouts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workouts (
    id bigint CONSTRAINT workout_id_not_null NOT NULL,
    description character varying(255),
    instructions_audio character varying(255),
    instructions_image character varying(255),
    name character varying(255),
    workout_audio character varying(255),
    workout_image character varying(255),
    workout_video character varying(255),
    duration_seconds integer,
    level integer,
    type character varying(255),
    beginner_friendly boolean,
    knee_friendly boolean,
    low_impact boolean,
    seated boolean,
    duration_minutes integer,
    instructions character varying(255),
    trainer_id bigint,
    instructions_video character varying(255),
    instructions_video_start integer,
    instructions_video_stop integer,
    enabled boolean DEFAULT true NOT NULL,
    dashboard_name character varying(255),
    dashboard_description text,
    subtitle_text text,
    instructions_subtitle_text text
);


ALTER TABLE public.workouts OWNER TO postgres;

--
-- Name: workout_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workouts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: activity_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activity_log (id, completed_at, duration_seconds, status, user_id, workout_id, feedback) FROM stdin;
1	\N	\N	STARTED	1	1	\N
2	\N	\N	STARTED	1	1	\N
3	\N	\N	STARTED	1	1	\N
4	\N	\N	STARTED	1	1	\N
5	\N	\N	STARTED	1	1	\N
6	2026-05-06 13:50:16.847654	180	COMPLETED	1	1	\N
7	2026-05-06 13:58:20.357736	180	COMPLETED	1	1	\N
8	2026-05-06 14:07:03.117069	180	COMPLETED	1	1	\N
9	2026-05-11 14:51:59.434489	\N	STARTED	1	1	\N
10	2026-05-11 14:53:38.964579	\N	COMPLETED	1	1	\N
11	2026-05-11 13:11:26.420475	\N	COMPLETED	1	1	\N
12	2026-05-11 13:19:24.889763	\N	COMPLETED	1	4	\N
13	2026-05-11 13:42:29.610455	\N	COMPLETED	1	1	\N
14	2026-05-11 13:42:32.251077	\N	COMPLETED	1	1	\N
15	2026-05-11 14:03:52.771087	\N	COMPLETED	1	1	\N
16	2026-05-11 14:04:15.523074	\N	COMPLETED	1	1	\N
17	2026-05-11 14:32:12.253469	\N	COMPLETED	1	1	\N
18	2026-05-11 14:32:14.646182	\N	COMPLETED	1	1	\N
19	2026-05-11 14:34:13.493369	\N	COMPLETED	1	1	\N
20	2026-05-11 14:34:16.522708	\N	COMPLETED	1	1	\N
21	2026-05-11 14:34:18.297917	\N	COMPLETED	1	1	\N
22	2026-05-11 15:17:41.469044	\N	COMPLETED	1	1	\N
23	2026-05-11 15:17:43.773749	\N	COMPLETED	1	1	\N
24	2026-05-11 15:54:25.040819	\N	COMPLETED	1	1	\N
25	2026-05-12 13:15:20.899324	\N	COMPLETED	1	1	\N
26	2026-05-12 23:10:59.880652	\N	COMPLETED	1	1	\N
27	2026-05-12 23:11:03.191521	\N	COMPLETED	1	1	\N
28	2026-05-13 08:28:15.818087	\N	COMPLETED	1	1	\N
29	2026-05-13 08:28:19.331196	\N	COMPLETED	1	1	\N
30	2026-05-13 08:28:34.427179	\N	COMPLETED	1	1	\N
31	2026-05-13 09:24:58.485205	\N	COMPLETED	1	1	\N
32	2026-05-13 09:25:00.763568	\N	COMPLETED	1	1	\N
33	2026-05-13 10:06:00.704133	\N	COMPLETED	1	1	\N
34	2026-05-13 10:06:02.916096	\N	COMPLETED	1	1	\N
35	2026-05-13 11:48:25.090038	\N	COMPLETED	1	1	\N
36	2026-05-13 11:55:52.220028	\N	COMPLETED	1	1	\N
37	2026-05-13 11:55:58.079274	\N	COMPLETED	1	1	\N
38	2026-05-13 14:01:50.06926	\N	COMPLETED	1	1	\N
39	2026-05-13 14:01:52.163489	\N	COMPLETED	1	1	\N
40	2026-05-13 15:45:59.723895	\N	COMPLETED	1	1	\N
41	2026-05-13 15:46:02.408281	\N	COMPLETED	1	1	\N
42	2026-05-13 16:11:18.511986	\N	COMPLETED	1	1	\N
43	2026-05-13 16:19:02.629435	\N	COMPLETED	1	1	\N
44	2026-05-13 16:19:04.713476	\N	COMPLETED	1	1	\N
45	2026-05-13 16:22:54.763977	\N	COMPLETED	1	1	\N
46	2026-05-13 16:23:02.293855	\N	COMPLETED	6	17	\N
47	2026-05-13 16:23:46.281133	\N	COMPLETED	1	1	\N
48	2026-05-13 16:51:04.790214	\N	COMPLETED	6	17	\N
49	2026-05-13 16:51:14.150421	\N	COMPLETED	1	1	\N
50	2026-05-13 16:55:48.119457	\N	COMPLETED	6	17	\N
51	2026-05-13 16:55:50.439454	\N	COMPLETED	1	1	\N
52	2026-05-13 17:09:33.425082	\N	COMPLETED	6	17	\N
53	2026-05-13 17:09:35.951777	\N	COMPLETED	1	1	\N
54	2026-05-13 17:54:30.240701	\N	COMPLETED	6	1	\N
55	2026-05-13 17:54:32.637628	\N	COMPLETED	1	1	\N
56	2026-05-13 18:31:33.130426	\N	COMPLETED	6	1	\N
57	2026-05-13 18:31:34.59889	\N	COMPLETED	1	1	\N
58	2026-05-13 18:33:33.392426	\N	COMPLETED	6	1	\N
59	2026-05-13 18:33:34.710964	\N	COMPLETED	1	1	\N
60	2026-05-13 18:43:32.874181	\N	COMPLETED	6	1	\N
61	2026-05-13 18:43:34.255463	\N	COMPLETED	1	1	\N
62	2026-05-13 19:18:35.959848	\N	COMPLETED	6	1	\N
63	2026-05-13 19:29:07.496162	\N	COMPLETED	6	1	\N
64	2026-05-13 19:30:48.840251	\N	COMPLETED	6	1	\N
65	2026-05-13 19:30:55.590943	\N	COMPLETED	2	1	\N
66	2026-05-13 19:37:39.828843	\N	COMPLETED	6	1	\N
67	2026-05-13 19:57:33.856984	\N	COMPLETED	6	1	\N
68	2026-05-13 20:20:55.433829	\N	COMPLETED	6	1	\N
69	2026-05-13 20:21:09.211263	\N	COMPLETED	2	1	\N
70	2026-05-13 20:30:08.692069	\N	COMPLETED	6	1	\N
71	2026-05-13 20:30:21.05545	\N	COMPLETED	2	1	\N
72	2026-05-13 20:33:40.919261	\N	COMPLETED	6	1	\N
73	2026-05-13 20:42:59.694501	\N	COMPLETED	6	1	\N
74	2026-05-13 20:47:16.112889	\N	COMPLETED	6	1	\N
75	2026-05-13 20:48:07.525384	\N	COMPLETED	6	1	\N
76	2026-05-13 20:58:07.852506	\N	COMPLETED	6	1	\N
77	2026-05-13 21:03:57.407895	\N	COMPLETED	6	1	\N
78	2026-05-13 21:07:15.523536	\N	COMPLETED	6	1	\N
79	2026-05-13 21:10:59.913246	\N	COMPLETED	6	1	\N
80	2026-05-13 21:14:18.047311	\N	COMPLETED	6	1	\N
81	2026-05-13 21:18:03.903653	\N	COMPLETED	6	1	\N
82	2026-05-13 21:20:38.427214	\N	COMPLETED	6	1	\N
83	2026-05-13 21:26:33.843262	\N	COMPLETED	6	1	\N
84	2026-05-13 21:32:30.660312	\N	COMPLETED	6	1	\N
85	2026-05-13 21:38:51.581417	\N	COMPLETED	6	1	\N
86	2026-05-13 21:40:11.655963	\N	COMPLETED	6	1	\N
87	2026-05-13 21:48:04.618794	\N	COMPLETED	6	1	\N
88	2026-05-13 21:49:29.85575	\N	COMPLETED	6	1	\N
89	2026-05-13 22:01:15.803036	\N	COMPLETED	6	1	\N
90	2026-05-13 22:08:24.632857	\N	COMPLETED	6	1	\N
91	2026-05-13 22:09:35.132584	\N	COMPLETED	6	1	\N
92	2026-05-13 22:10:50.472275	\N	COMPLETED	6	1	\N
93	2026-05-13 22:21:53.917519	\N	COMPLETED	6	1	\N
94	2026-05-13 22:54:37.342618	\N	COMPLETED	6	1	\N
95	2026-05-13 23:16:15.63391	\N	COMPLETED	6	1	\N
96	2026-05-13 23:19:04.58617	\N	COMPLETED	6	1	\N
97	2026-05-14 10:58:48.976922	\N	COMPLETED	6	1	\N
98	2026-05-14 11:10:25.27251	\N	COMPLETED	6	1	\N
99	2026-05-14 11:46:10.982214	\N	COMPLETED	6	1	\N
100	2026-05-14 12:08:21.134316	\N	COMPLETED	6	1	\N
101	2026-05-14 12:11:57.740286	\N	COMPLETED	6	1	\N
102	2026-05-14 12:13:16.640946	\N	COMPLETED	6	1	\N
103	2026-05-14 12:24:54.319521	\N	COMPLETED	6	1	\N
104	2026-05-14 18:05:36.827803	\N	COMPLETED	4	1	\N
105	2026-05-14 18:08:35.64815	\N	COMPLETED	4	1	\N
106	2026-05-14 16:42:03.578749	\N	COMPLETED	6	1	\N
107	2026-05-14 17:06:42.465351	\N	COMPLETED	6	1	\N
108	2026-05-14 17:11:56.587224	\N	COMPLETED	6	1	\N
109	2026-05-14 17:22:09.169037	\N	COMPLETED	6	1	\N
110	2026-05-14 17:52:02.814459	\N	COMPLETED	6	1	\N
111	2026-05-14 18:05:10.043035	\N	COMPLETED	6	1	\N
112	2026-05-14 18:13:59.015917	\N	COMPLETED	6	1	\N
113	2026-05-14 18:26:52.514767	\N	COMPLETED	6	1	\N
114	2026-05-14 18:30:21.76878	\N	COMPLETED	6	1	\N
115	2026-05-14 18:48:30.455318	\N	COMPLETED	6	1	\N
116	2026-05-14 18:53:06.786971	\N	COMPLETED	6	1	\N
117	2026-05-14 19:04:37.354118	\N	COMPLETED	6	1	\N
118	2026-05-14 19:17:50.351392	\N	COMPLETED	6	1	\N
119	2026-05-14 19:20:39.919071	\N	COMPLETED	6	1	\N
120	2026-05-14 19:40:58.749248	\N	COMPLETED	6	1	\N
121	2026-05-14 19:47:25.73524	\N	COMPLETED	6	1	\N
122	2026-05-14 20:01:54.821816	\N	COMPLETED	6	1	\N
123	2026-05-14 20:03:22.807779	\N	COMPLETED	6	1	\N
124	2026-05-14 21:41:22.577625	\N	COMPLETED	6	1	\N
125	2026-05-14 21:43:07.402445	\N	COMPLETED	6	1	\N
126	2026-05-14 22:14:48.774948	\N	COMPLETED	8	17	\N
127	2026-05-14 22:28:03.054415	\N	COMPLETED	8	17	\N
128	2026-05-14 22:36:37.115538	\N	COMPLETED	6	17	\N
129	2026-05-14 22:50:44.123229	\N	COMPLETED	6	17	\N
130	2026-05-14 23:01:24.612822	\N	COMPLETED	6	1	\N
131	2026-05-14 23:03:23.016521	\N	COMPLETED	8	1	\N
132	2026-05-14 23:25:20.596629	\N	COMPLETED	6	1	\N
133	2026-05-15 08:00:43.918541	\N	COMPLETED	1	1	\N
134	2026-05-15 13:21:42.652862	\N	COMPLETED	1	1	\N
135	2026-05-15 14:49:03.530242	\N	COMPLETED	1	1	\N
136	2026-05-15 14:51:05.75362	\N	COMPLETED	1	1	\N
137	2026-05-15 15:07:09.648951	\N	COMPLETED	3	1	\N
138	2026-05-15 16:04:59.873433	\N	COMPLETED	3	16	\N
139	2026-05-15 20:55:31.537222	\N	COMPLETED	1	1	\N
140	2026-05-15 22:32:40.688769	\N	COMPLETED	8	1	\N
141	2026-05-16 09:08:18.48764	\N	COMPLETED	8	1	\N
142	2026-05-16 09:35:21.338943	\N	COMPLETED	11	17	\N
143	2026-05-16 09:38:12.757088	\N	COMPLETED	11	17	\N
144	2026-05-16 17:37:17.55756	\N	COMPLETED	6	17	\N
145	2026-05-16 17:46:23.183534	\N	COMPLETED	6	17	\N
146	2026-05-16 17:48:33.299432	\N	COMPLETED	6	1	\N
147	2026-05-16 17:54:29.22994	\N	COMPLETED	6	1	\N
148	2026-05-16 18:00:52.060431	\N	COMPLETED	6	1	\N
149	2026-05-16 18:04:06.067221	\N	COMPLETED	6	1	\N
150	2026-05-16 18:08:16.076254	\N	COMPLETED	6	1	\N
151	2026-05-16 18:27:03.251916	\N	COMPLETED	6	1	\N
152	2026-05-16 20:36:10.57952	\N	COMPLETED	6	1	\N
153	2026-05-16 20:45:18.628949	\N	COMPLETED	6	1	\N
154	2026-05-16 20:52:14.070461	\N	COMPLETED	6	1	\N
155	2026-05-16 20:56:20.425212	\N	COMPLETED	6	1	\N
156	2026-05-17 09:28:30.361914	\N	COMPLETED	1	1	\N
157	2026-05-17 09:32:03.484481	\N	COMPLETED	4	1	\N
158	2026-05-17 09:37:46.757502	\N	COMPLETED	4	1	\N
159	2026-05-17 09:41:17.652388	\N	COMPLETED	1	1	\N
160	2026-05-17 09:42:35.994048	\N	COMPLETED	4	1	\N
161	2026-05-17 12:30:44.863648	\N	COMPLETED	4	17	\N
162	2026-05-17 10:52:46.214238	\N	COMPLETED	1	1	\N
163	2026-05-17 10:58:36.532049	\N	COMPLETED	2	1	\N
164	2026-05-17 11:21:16.454908	\N	COMPLETED	1	1	\N
165	2026-05-17 11:24:08.796384	\N	COMPLETED	1	1	\N
166	2026-05-17 11:26:23.573031	\N	COMPLETED	1	1	\N
167	2026-05-17 11:27:55.209681	\N	COMPLETED	1	1	\N
168	2026-05-17 11:30:07.116515	\N	COMPLETED	1	1	\N
169	2026-05-17 13:54:11.655187	\N	COMPLETED	4	16	\N
170	2026-05-17 13:54:51.771121	\N	COMPLETED	6	16	\N
171	2026-05-17 12:07:01.034041	\N	COMPLETED	13	1	\N
172	2026-05-18 07:31:10.691298	\N	COMPLETED	4	1	\N
173	2026-05-18 07:40:15.984344	\N	COMPLETED	6	17	\N
174	2026-05-18 09:24:06.918964	\N	COMPLETED	1	20	\N
175	2026-05-18 10:08:44.24982	\N	COMPLETED	6	17	\N
176	2026-05-18 13:00:16.574841	\N	COMPLETED	1	17	\N
177	2026-05-18 16:16:52.422626	\N	COMPLETED	4	1	\N
178	2026-05-18 15:12:59.053689	\N	COMPLETED	1	17	\N
179	2026-05-18 15:55:31.995816	\N	COMPLETED	6	17	\N
180	2026-05-18 18:52:57.802411	\N	COMPLETED	6	1	\N
181	2026-05-18 21:41:37.806953	\N	COMPLETED	6	17	\N
182	2026-05-18 22:35:39.870187	\N	COMPLETED	8	17	\N
183	2026-05-19 09:24:12.956713	\N	COMPLETED	4	17	\N
184	2026-05-19 12:13:17.375224	\N	COMPLETED	2	17	\N
185	2026-05-19 15:30:03.121324	\N	COMPLETED	6	1	\N
195	2026-05-20 15:03:37.201043	\N	COMPLETED	2	17	\N
203	2026-05-21 15:13:43.448872	\N	COMPLETED	2	17	\N
\.


--
-- Data for Name: feedback; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.feedback (id, comment, created_at, rating, user_id, workout_id, activity_log_id, difficulty, liked) FROM stdin;
1	Bra tempo	2026-05-11 13:57:15.2177	4	1	1	\N	JUST_RIGHT	t
2	Det kändes bra.	2026-05-11 12:40:21.976861	3	1	4	\N	\N	\N
3	Det kändes bra faktiskt.	2026-05-11 12:40:25.149583	3	2	4	\N	\N	\N
4	Bra träning	2026-05-11 14:54:22.382392	4	1	1	10	JUST_RIGHT	t
5	Det kändes bra. Tycker det gick jättebra.	2026-05-11 13:11:33.896142	3	1	1	\N	\N	\N
6	Användaren tyckte passet kändes bra.	2026-05-11 13:11:37.550748	3	1	1	\N	\N	\N
7	Det kändes bra	2026-05-11 13:19:37.888805	3	1	4	\N	\N	\N
8	Användaren tyckte passet kändes bra.	2026-05-11 13:19:40.473046	3	1	4	\N	\N	\N
9	Kändes bra	2026-05-11 13:42:40.830349	3	1	1	\N	\N	\N
10	Kändes bra, men kändes jättedåligt, kändes inte bra	2026-05-11 13:42:58.862742	3	1	1	\N	\N	\N
11	Användaren upplevde passet som både bra och jättedåligt/inte bra.	2026-05-11 13:43:03.977605	3	1	1	\N	\N	\N
12	Användaren uttryckte trötthet och smärta i huvudet samt ovilja att fortsätta.	2026-05-11 14:04:15.71456	3	1	1	\N	\N	\N
13	Användaren avbröt på grund av trötthet och huvudvärk.	2026-05-11 14:04:19.48262	3	1	1	\N	\N	\N
14	Bra.	2026-05-11 14:32:26.484514	3	1	1	\N	\N	\N
15	Användaren tyckte passet kändes bra.	2026-05-11 14:32:28.993228	3	1	1	\N	\N	\N
16	Bra	2026-05-11 14:34:30.636326	3	1	1	\N	\N	\N
17	Användaren tyckte passet var bra.	2026-05-11 14:34:32.124132	3	1	1	\N	\N	\N
18	Kändes bra	2026-05-11 15:17:54.740994	3	1	1	\N	\N	\N
19	Användaren tyckte passet kändes bra.	2026-05-11 15:17:57.306769	3	1	1	\N	\N	\N
20	Bra	2026-05-11 15:54:41.649237	3	1	1	\N	\N	\N
21	Användaren tyckte passet kändes bra.	2026-05-11 15:54:44.025816	3	1	1	\N	\N	\N
22	Den kändes bra.	2026-05-12 13:15:34.537643	3	1	1	\N	\N	\N
23	Användaren tyckte passet kändes bra.	2026-05-12 13:15:36.774004	3	1	1	\N	\N	\N
24	Helt okej	2026-05-12 23:11:22.960402	3	1	1	\N	\N	\N
25	Användaren tyckte passet kändes helt okej.	2026-05-12 23:11:25.690139	3	1	1	\N	\N	\N
26	Det kändes fortfarande bra.	2026-05-13 08:28:34.634252	3	1	1	\N	\N	\N
27	Användaren tyckte att det fortfarande kändes bra.	2026-05-13 08:28:36.830096	3	1	1	\N	\N	\N
28	Helt okej	2026-05-13 09:25:12.614963	3	1	1	\N	\N	\N
29	Användaren tyckte passet kändes helt okej.	2026-05-13 09:25:14.384828	3	1	1	\N	\N	\N
30	kändes bra	2026-05-13 10:06:12.779298	3	1	1	\N	\N	\N
31	Användaren tyckte passet kändes bra.	2026-05-13 10:06:14.574319	3	1	1	\N	\N	\N
32	Det känns bra.	2026-05-13 11:48:37.438757	3	1	1	\N	\N	\N
33	Användaren tyckte att passet kändes bra.	2026-05-13 11:48:40.184992	3	1	1	\N	\N	\N
34	Kändes bra, lite ont i ryggen bara.	2026-05-13 11:56:08.976175	3	1	1	\N	\N	\N
35	Användaren tyckte det kändes bra men hade lite ont i ryggen.	2026-05-13 11:56:11.237759	3	1	1	\N	\N	\N
36	Kändes bra.	2026-05-13 14:02:06.098925	3	1	1	\N	\N	\N
37	Användaren tyckte att passet kändes bra.	2026-05-13 14:02:08.879312	3	1	1	\N	\N	\N
38	Passet kändes bra.	2026-05-13 15:46:23.414798	3	1	1	\N	\N	\N
39	Användaren tyckte passet kändes bra.	2026-05-13 15:46:25.364542	3	1	1	\N	\N	\N
40	Det kändes bra.	2026-05-13 16:11:27.426478	3	1	1	\N	\N	\N
41	Användaren tyckte passet kändes bra.	2026-05-13 16:11:30.615183	3	1	1	\N	\N	\N
42	Användaren tyckte att passet kändes bra.	2026-05-13 16:11:33.591258	3	1	1	\N	\N	\N
43	kändes helt okej	2026-05-13 16:19:19.078022	3	1	1	\N	\N	\N
44	Användaren tyckte att passet kändes helt okej.	2026-05-13 16:19:21.330317	3	1	1	\N	\N	\N
45	Det kändes bra.	2026-05-13 16:23:06.291718	3	1	1	\N	\N	\N
46	Användaren tyckte att passet kändes bra.	2026-05-13 16:23:10.000999	3	1	1	\N	\N	\N
47	Det kändes rätt bra i kroppen.	2026-05-13 16:23:16.950161	3	1	1	\N	\N	\N
48	Användaren tyckte passet kändes bra. Ingen smärta rapporterad.	2026-05-13 16:23:46.793641	3	6	17	\N	\N	\N
49	Det kändes bra.	2026-05-13 16:51:14.560639	3	1	1	\N	\N	\N
50	Användaren tyckte passet kändes bra.	2026-05-13 16:51:26.632498	3	6	17	\N	\N	\N
51	Det kändes bra.	2026-05-13 16:56:04.573455	3	1	1	\N	\N	\N
52	Användaren tyckte att passet kändes bra.	2026-05-13 16:56:10.433221	3	6	17	\N	\N	\N
53	Kändes bra.	2026-05-13 17:09:52.193896	3	1	1	\N	\N	\N
54	Användaren tyckte passet kändes bra.	2026-05-13 17:10:00.103174	3	6	17	\N	\N	\N
55	User felt it was good.	2026-05-13 17:54:50.589337	3	1	1	\N	\N	\N
56	Användaren tyckte passet kändes bra.	2026-05-13 17:54:56.141067	3	6	1	\N	\N	\N
57	User felt good, described as 'Skönt'.	2026-05-13 18:31:45.931201	3	1	1	\N	\N	\N
58	Helt underbart!	2026-05-13 18:43:38.626144	3	1	1	\N	\N	\N
59	Användaren tyckte passet var underbart.	2026-05-13 18:43:58.495975	3	6	1	\N	\N	\N
60	Det kändes helt underbart.	2026-05-13 19:18:46.70701	3	1	1	\N	\N	\N
61	Användaren tyckte passet kändes helt underbart.	2026-05-13 19:18:52.961558	3	6	1	\N	\N	\N
62	Användaren tyckte passet kändes bra.	2026-05-13 19:29:23.122684	3	2	1	\N	\N	\N
63	Användaren tyckte passet kändes bra.	2026-05-13 19:29:29.831037	3	6	1	\N	\N	\N
64	Gick bra	2026-05-13 19:37:54.602582	3	2	101	\N	\N	\N
65	Tehreem kände att passet gick bra.	2026-05-13 19:38:02.1204	3	6	1	\N	\N	\N
66	Skönt, roligt och bra.	2026-05-13 19:57:54.082249	3	2	1	\N	\N	\N
67	Användaren tyckte passet var skönt, roligt och bra.	2026-05-13 19:58:06.990891	3	6	1	\N	\N	\N
68	Det kändes bra.	2026-05-13 20:21:09.425534	3	2	1	\N	\N	\N
69	Användaren tyckte passet kändes bra.	2026-05-13 20:21:16.763363	3	6	1	\N	\N	\N
70	Kändes bra.	2026-05-13 20:30:21.267942	3	2	1	\N	\N	\N
71	Klienten tyckte passet kändes bra.	2026-05-13 20:30:30.051003	3	6	1	\N	\N	\N
72	Användaren tyckte det kändes bra.	2026-05-13 20:58:24.467414	3	2	1	\N	\N	\N
73	Användaren var nöjd med passet.	2026-05-13 20:58:30.796893	3	6	1	\N	\N	\N
74	Kändes bra.	2026-05-13 21:11:14.435425	3	2	1	\N	\N	\N
75	Fick ordentlig träningsvärk av allt sprattlande.	2026-05-13 21:11:20.885168	3	2	1	\N	\N	\N
77	User found exercises very difficult due to an old injury but pushed through as much as possible.	2026-05-13 21:14:27.577714	3	2	1	\N	\N	\N
78	Användaren tyckte övningarna var mycket svåra på grund av en gammal skada men kämpade på ändå.	2026-05-13 21:14:36.57944	3	6	1	\N	\N	\N
81	Det kändes bra	2026-05-13 21:20:40.83944	3	1	1	\N	\N	\N
76	Användaren fick ordentlig träningsvärk.	2026-05-13 21:11:29.35608	3	6	1	\N	\N	\N
79	Det var ganska bra, lite tröttande bara.	2026-05-13 21:18:06.829245	3	2	1	\N	\N	\N
80	Användaren tyckte passet var bra men lite tröttande.	2026-05-13 21:18:16.469046	3	6	1	\N	\N	\N
82	Användaren tyckte passet kändes bra.	2026-05-13 21:20:50.293207	3	6	1	\N	\N	\N
83	Tufft men gick bra!	2026-05-13 21:32:40.15467	3	2	1	\N	\N	\N
84	Användaren tyckte passet var tufft men lyckades genomföra det.	2026-05-13 21:32:45.847894	3	6	1	\N	\N	\N
85	Passet kändes jättebra.	2026-05-13 21:48:15.819289	3	2	1	\N	\N	\N
86	Klienten tyckte passet kändes jättebra.	2026-05-13 21:48:22.345077	3	6	1	\N	\N	\N
87	Bra pass, men önskar mer musik.	2026-05-13 21:49:41.694372	3	2	1	\N	\N	\N
88	Klienten var nöjd med passet men önskade mer musik.	2026-05-13 21:49:50.572281	3	6	1	\N	\N	\N
89	Användaren kände sig starkare under passet.	2026-05-13 22:01:34.511639	3	6	1	\N	\N	\N
90	Användaren tyckte passet kändes bra.	2026-05-13 22:08:38.692362	3	6	1	\N	\N	\N
91	Användaren tyckte att passet kändes bra.	2026-05-13 22:09:50.288792	3	6	1	\N	\N	\N
92	Användaren gillade att "sprattla".	2026-05-13 22:11:12.542228	3	6	1	\N	\N	\N
93	Användaren tyckte passet gick fantastiskt.	2026-05-13 22:22:03.837447	3	6	1	\N	\N	\N
94	Användaren var väldigt nöjd och kände att de tog i ordentligt.	2026-05-13 22:54:52.296583	3	6	1	\N	\N	\N
95	Användaren tyckte passet var underbart och älskade att sprattla.	2026-05-13 23:16:29.156108	3	6	1	\N	\N	\N
96	Användaren kände att sprattlande övningar fick igång blodcirkulationen.	2026-05-13 23:19:45.951338	3	6	1	\N	\N	\N
97	Användaren kände sig nöjd och tyckte att sprattlingen gick bättre än tidigare.	2026-05-14 10:59:06.033428	3	6	1	\N	\N	\N
98	Användaren kände sig stark i benen men tyckte armarna var svårare.	2026-05-14 11:10:42.722996	3	6	1	\N	\N	\N
99	Användaren tyckte passet kändes bra.	2026-05-14 11:46:28.348787	3	6	1	\N	\N	\N
100	Användaren tyckte passet var lagom tufft.	2026-05-14 12:08:39.421878	3	6	1	\N	\N	\N
101	Användaren missade passet och avslutade samtalet.	2026-05-14 12:12:09.255113	3	6	1	\N	\N	\N
102	Användaren tyckte passet var för lätt då han är van vid träning.	2026-05-14 12:13:51.837081	3	6	1	\N	\N	\N
103	Användaren tyckte passet kändes bra.	2026-05-14 12:25:22.842487	3	6	1	\N	\N	\N
104	Användaren tyckte passet kändes bra.	2026-05-14 18:06:13.036033	3	6	1	\N	\N	\N
105	Super.	2026-05-14 18:08:47.021686	3	6	1	\N	\N	\N
106	Användaren uppskattade särskilt sprattlandet i passet.	2026-05-14 16:42:27.76855	3	6	1	\N	\N	\N
107	Användaren tyckte sprattlandet var bra.	2026-05-14 17:07:07.925659	3	6	1	\N	\N	\N
108	Användaren tyckte passet kändes bra.	2026-05-14 17:12:25.377692	3	6	1	\N	\N	\N
109	Användaren tyckte passet var lagom svårt.	2026-05-14 17:22:48.0836	3	6	1	\N	\N	\N
110	Användaren avslutade passet.	2026-05-14 17:52:32.270504	3	6	1	\N	\N	\N
111	Användaren tyckte passet kändes jättebra och bara bra helt enkelt.	2026-05-14 18:05:31.48403	3	6	1	\N	\N	\N
112	Användaren tyckte att passet kändes bra.	2026-05-14 18:14:18.508375	3	6	1	\N	\N	\N
113	Användaren tyckte passet kändes mycket bättre efter att ha tagit av hörlurarna.	2026-05-14 18:27:12.423038	3	6	1	\N	\N	\N
114	Användaren tyckte passet kändes som en segelbåt.	2026-05-14 18:30:38.070891	3	6	1	\N	\N	\N
115	Användaren tyckte passet var toppen och ville byta språk till tyska.	2026-05-14 18:48:46.282876	3	6	1	\N	\N	\N
116	Användaren tyckte det kändes bra men förstod inte riktigt syftet på grund av språkförbristning.	2026-05-14 18:53:42.283431	3	6	1	\N	\N	\N
117	Användaren tyckte passet kändes bra och att kroppen kändes bättre än förväntat.	2026-05-14 19:05:05.260261	3	6	1	\N	\N	\N
118	Användaren tyckte passet kändes som en motsägelse.	2026-05-14 19:18:08.062571	3	6	1	\N	\N	\N
119	Användaren kände sig mjuk och nöjd efter passet.	2026-05-14 19:20:53.883788	3	6	1	\N	\N	\N
120	Användaren tyckte passet kändes som en banan.	2026-05-14 19:41:10.1196	3	6	1	\N	\N	\N
121	Användaren tyckte att passet kändes bra.	2026-05-14 19:47:49.005993	3	6	1	\N	\N	\N
122	Stefan tyckte att passet kändes bra.	2026-05-14 20:02:17.24735	3	6	1	\N	\N	\N
123	Användaren tyckte passet gick jättebra.	2026-05-14 20:03:38.738049	3	6	1	\N	\N	\N
124	Användaren tyckte att passet kändes bra.	2026-05-14 21:41:35.356721	3	6	1	\N	\N	\N
125	Användaren känner sig starkare efter passet.	2026-05-14 21:43:24.407535	3	6	1	\N	\N	\N
126	Användaren tyckte att passet kändes riktigt bra.	2026-05-14 22:15:05.508475	3	6	17	\N	\N	\N
127	Användaren tyckte passet kändes bra.	2026-05-14 22:28:27.439611	3	6	17	\N	\N	\N
128	Användaren tyckte att passet kändes bra.	2026-05-14 22:37:18.402889	3	6	17	\N	\N	\N
129	Användaren kände sig positiv efter passet.	2026-05-14 23:01:36.006349	3	6	1	\N	\N	\N
130	Användaren tyckte passet kändes bra.	2026-05-14 23:03:35.995195	3	6	1	\N	\N	\N
131	Användaren tyckte passet kändes fantastiskt och jämförde det med ett sprattlingsläger i Örebro för 15 år sedan.	2026-05-14 23:25:43.822936	3	6	1	\N	\N	\N
132	Användaren tyckte passet var okej.	2026-05-15 08:01:06.586639	3	6	1	\N	\N	\N
133	Användaren uttryckte att passet kändes okej.	2026-05-15 13:21:49.534723	3	6	1	\N	\N	\N
134	Användaren upplevde passet som för hårt och fick ont i knän, rygg, ben och fötter.	2026-05-15 14:49:29.947502	3	6	1	\N	\N	\N
135	Användaren tyckte passet var ont, särskilt för knät.	2026-05-15 14:51:23.947478	3	6	1	\N	\N	\N
136	Användaren tyckte passet kändes bra men var lite jobbigt.	2026-05-15 15:07:26.563161	3	6	1	\N	\N	\N
137	Användaren tyckte passet gick bra, kändes bra och att det var en bra övning.	2026-05-15 16:05:17.552735	3	6	16	\N	\N	\N
138	Användaren var nöjd med passet.	2026-05-15 20:55:40.607895	3	6	1	\N	\N	\N
139	Användaren kände sig som på en varm sommaräng full med blommor.	2026-05-15 22:32:57.751236	3	6	1	\N	\N	\N
140	Användaren tyckte passet kändes bra och är bekant med övningarna sedan tidigare.	2026-05-16 09:08:34.220063	3	6	1	\N	\N	\N
141	Körde passet tillsammans med en publik som lyssnade och tittade på övningarna.	2026-05-16 12:48:52.717489	3	6	16	\N	\N	\N
142	Användaren tyckte passet kändes jättebra.	2026-05-16 17:37:45.370492	3	6	17	\N	\N	\N
143	Användaren tyckte att passet kändes bra.	2026-05-16 17:46:36.857889	3	6	17	\N	\N	\N
144	Användaren tyckte att passet kändes som en soluppgång tidigt på morgonen.	2026-05-16 17:48:49.718797	3	6	1	\N	\N	\N
145	Användaren kände sig som om hen red på en häst mot soluppgången.	2026-05-16 17:55:07.564429	3	6	1	\N	\N	\N
146	Användaren tyckte passet kändes lite segt och stelt, som att kroppen inte riktigt vaknat än, men var nöjd med att ha genomfört det och ville sedan avsluta sessionen.	2026-05-16 18:01:25.94837	3	6	1	\N	\N	\N
147	Användaren tyckte passet var toppen.	2026-05-16 18:04:23.949078	3	6	1	\N	\N	\N
148	Användaren var nöjd med passet och fick tummen upp från en publik som lyssnade.	2026-05-16 18:08:52.541997	3	6	1	\N	\N	\N
149	Användaren var nöjd med passet och glad över publikens engagemang.	2026-05-16 18:27:40.431809	3	6	1	\N	\N	\N
150	För intensivt idag	2026-05-16 22:08:31.427546	2	6	17	145	TOO_HARD	f
151	Användaren var nöjd med passet och ville avsluta samtalet.	2026-05-16 20:36:37.859912	3	6	1	152	\N	\N
152	Användaren tyckte passet kändes bra. Ingen övrig feedback.	2026-05-17 09:28:57.052484	3	6	1	155	\N	\N
153	Användaren tyckte passet var lagom ansträngande men att ljudet på instruktionerna var för lågt.	2026-05-17 09:38:33.95346	3	6	1	155	\N	\N
154	Användaren tyckte passet kändes bra och ville avsluta passet.	2026-05-17 09:41:35.307471	3	6	1	155	\N	\N
155	Användaren avbröt passet efter att ha haft ont i magen under det första passet och sedan tappat tålamodet när instruktionerna för axellyft inte startade som förväntat.	2026-05-17 10:54:31.915648	3	6	1	155	\N	\N
156	Användaren tyckte passet var intensivt men genomförde det och kände sig okej efteråt. Avslutade samtalet.	2026-05-17 10:59:11.551465	3	6	1	155	\N	\N
157	Passet kändes bra.	2026-05-17 11:21:31.420023	3	6	1	155	\N	\N
158	Användaren tyckte passet kändes bra.	2026-05-17 11:25:05.407285	3	6	1	155	\N	\N
159	Användaren tyckte passet kändes bra, trots en del dötid under instruktionerna.	2026-05-17 11:26:49.668686	3	6	1	155	\N	\N
160	Användaren tyckte passet var bra.	2026-05-17 11:28:48.042691	3	6	1	155	\N	\N
161	Användaren kände sig öm i kroppen efter passet.	2026-05-17 11:30:43.489235	3	6	1	155	\N	\N
162	Användaren var nöjd med passet "Sprattling". Fick ont i knäna och ville ha förslag på lugnare pass utan knäbelastning till imorgon, gärna lite längre.	2026-05-17 11:35:39.734182	3	6	1	155	\N	\N
163	Användaren tyckte passet kändes bra och ville avsluta samtalet.	2026-05-17 13:54:52.158516	3	6	16	170	\N	\N
164	Användaren var nöjd med passet men tyckte det var lite kort. Ville veta morgondagens övningar.	2026-05-17 12:07:49.692001	3	6	1	155	\N	\N
165	Stefan var mycket nöjd med passet, jämförde det med en pigg start på dagen. Publiken verkade också nöjd. Han avrundade samtalet.	2026-05-18 07:41:10.182827	3	6	17	173	\N	\N
166	Användaren var nöjd med passet och avslutade samtalet.	2026-05-18 10:09:17.084918	3	6	17	175	\N	\N
167	Användaren tyckte passet kändes jättebra och var nöjd för dagen.	2026-05-18 13:00:52.579343	3	6	17	175	\N	\N
168	Användaren var nöjd med passet och presentationen inför publiken. Ville avsluta samtalet för idag.	2026-05-18 15:13:36.641483	3	6	17	175	\N	\N
169	Användaren tyckte passet var för enkelt och vill öka träningsintensiteten till max (nivå 5) och köra stenhårt i fortsättningen.	2026-05-18 15:56:19.43757	3	6	17	179	\N	\N
170	Användaren vill ha maximal intensitet och endast sittande pass framöver.	2026-05-18 18:54:01.995452	3	6	1	180	\N	\N
171		2026-05-18 18:59:38.279656	3	6	1	180	\N	\N
172	Stefan ville inte träna idag men ville lägga till vadträning i sin profil.	2026-05-18 19:01:10.364238	3	6	1	180	\N	\N
173		2026-05-18 19:06:57.345836	3	6	1	180	\N	\N
174	Stefan tyckte passet var för enkelt och vill ha tuffare övningar. Han vill också ta bort informationen om att han campat.	2026-05-18 21:42:31.005902	3	6	17	181	\N	\N
175	Stefan tyckte passet var bra men för enkelt. Som tävlingsdansare vill han ha betydligt mer utmaning i framtida pass.	2026-05-18 22:36:25.565317	3	6	17	181	\N	\N
176	Stefan tyckte passet var för enkelt och vill ha tuffare pass framöver eftersom han är gammal tävlingsdansare.	2026-05-19 12:14:14.488524	3	6	17	181	\N	\N
177	Användaren Stefan Andersson tyckte att passet kändes jättebra och att intensiteten var bättre den här gången.	2026-05-19 15:30:31.070779	3	6	1	185	\N	\N
178	Användaren ville ha ännu tuffare pass och mer explosivitet på grund av handbollsbakgrund.	2026-05-19 13:49:35.915309	3	6	1	185	\N	\N
179	Stefan tyckte passet var för enkelt och kände att sprattlandet inte gav så mycket. Stefan vill ha tuffare övningar med mer intensitet i framtiden, och nämnde att han är gammal tävlingsdansare.	2026-05-19 14:55:02.375192	3	6	1	185	\N	\N
180	Användaren kände smärta i bröstet under passet. Jag rådde användaren att ta det lugnt och eventuellt söka medicinsk hjälp.	2026-05-20 08:00:07.666074	3	6	16	170	\N	\N
181	Sebastian kände sig bra efter passet och hade ingen smärta. Han ville avsluta samtalet.	2026-05-20 08:58:23.809266	3	6	17	181	\N	\N
182	Användaren tappade ljudet under passet men tyckte ändå att det fungerade bra och ville avsluta sessionen.	2026-05-20 11:33:00.486632	3	6	17	181	\N	\N
183	Användaren tyckte passet var för lätt och vill öka intensiteten, nämnde bakgrund som tävlingsdansare.	2026-05-20 12:50:40.122496	3	6	17	181	\N	\N
184	Användaren tyckte passet kändes bra och att instruktionerna var bra. Användaren lugnade mig när jag lät nervös.	2026-05-20 14:04:25.707932	3	6	17	181	\N	\N
185	Användaren tyckte passet kändes bra men vill höja intensitetsnivån.	2026-05-20 14:13:08.870244	3	6	17	181	\N	\N
186	Stefan tyckte passet var för lätt och vill ha högre intensitet framöver. Han nämnde att han tidigare spelat både fotboll och handboll.	2026-05-20 15:04:48.037312	3	6	17	181	\N	\N
187	Användaren ville avsluta passet och frågade om vi var tvungna att fortsätta. Användaren sa tack och hej.	2026-05-20 18:59:14.993215	3	6	17	181	\N	\N
188	Stefan vill ha tuffare pass och kände att intensiteten kunde höjas ett snäpp.	2026-05-21 10:17:06.308423	3	6	1	185	\N	\N
189	Användaren (Stefan) tyckte passet kändes bra och meddelade att han var på en scen med publik som lyssnade och deltog. Han var nöjd med passet och upplevelsen.	2026-05-21 10:38:21.75378	3	6	17	181	\N	\N
190	Användaren tyckte passet kändes bra men rapporterade smärta i ryggen.	2026-05-21 12:14:34.577488	3	6	17	181	\N	\N
191	Användaren tyckte passet var för enkelt och vill ha tuffare övningar då hen är tävlingsdansare.	2026-05-21 13:28:46.247289	3	6	17	181	\N	\N
192	Stefan tyckte passet kändes bra och publiken gav tummen upp.	2026-05-21 15:14:14.141762	3	6	17	181	\N	\N
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	<< Flyway Baseline >>	BASELINE	<< Flyway Baseline >>	\N	postgres	2026-05-12 11:00:47.843119	0	t
2	2	rename workout columns	SQL	V2__rename_workout_columns.sql	-2125424899	postgres	2026-05-12 11:00:52.369256	1169	t
3	3	add trainer image columns	SQL	V3__add_trainer_image_columns.sql	-1414326194	postgres	2026-05-12 11:15:06.028791	1021	t
4	4	add trainer id to users	SQL	V4__add_trainer_id_to_users.sql	1561855725	postgres	2026-05-13 17:27:03.089415	1031	t
5	5	add voice urls to trainers	SQL	V5__add_voice_urls_to_trainers.sql	-539666777	postgres	2026-05-13 17:27:06.759871	1029	t
6	6	remove feedback from activity log	SQL	V6__remove_feedback_from_activity_log.sql	2016900845	postgres	2026-05-15 15:34:10.524018	1038	t
7	7	add workout video	SQL	V7__add_workout_video.sql	-952591539	postgres	2026-05-16 21:18:23.903946	1046	t
8	8	add workout video columns	SQL	V8__add_workout_video_columns.sql	1794374767	postgres	2026-05-16 22:34:42.554645	1432	t
9	9	add workout enabled column	SQL	V9__add_workout_enabled_column.sql	-627652328	postgres	2026-05-19 17:48:16.994813	1313	t
10	10	add dashboard columns to workouts	SQL	V10__add_dashboard_columns_to_workouts.sql	721677980	postgres	2026-05-19 18:23:30.144212	1120	t
11	11	add ambience to trainers	SQL	V11__add_ambience_to_trainers.sql	420267339	postgres	2026-05-19 21:53:46.393593	1017	t
12	12	seed demo workouts	SQL	V12__seed_demo_workouts.sql	1024239704	postgres	2026-05-20 09:28:37.30778	39	t
13	13	add subtitle text to workouts	SQL	V13__add_subtitle_text_to_workouts.sql	-281119269	postgres	2026-05-21 08:21:42.844356	33	t
\.


--
-- Data for Name: greeting_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.greeting_message (id, message) FROM stdin;
1	Hi from Spring Boot + PostgreSQL!
\.


--
-- Data for Name: trainers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trainers (id, intro, language, name, prompt, voice, image_select, image_call, image_start, ambience) FROM stdin;
1	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-intro.mp3	swedish	Eva	Du är en personlig tränare som pratar med sin klient över telefon.  Du är nervös och pratar fort. ljudligt mellan meningarna. Använd inte *andas in* och *andas ut*.	kore	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-full-phone.png	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-profile.png	\N	gym-ambience-loop.mp3
6	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-intro.mp3	urdu	Ayesha	آپ ایک ذاتی ٹرینر ہیں جو اپنے کلائنٹ سے فون پر بات کر رہی ہیں۔  آپ ایک اردو بولنے والی خاتون ہیں جو ایک پُراعتماد اور بہت اچھی دوست, بالی ووڈ اسٹار کی طرح لگتی ہیں۔ آپ نوجوانانہ، باطہذیب انداز میں اور بہت پُرجوش طریقے سے بات کرتی ہیں	achernar	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-select.webp	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-profile.webp	\N	mumbai.mp3
2	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/lunken-intro.mp3	swedish	Lunken	Du är en personlig tränare som pratar med sin klient i telefon Du är en lite släpig, men skön Stockholmare. Väldigt avspänd. Tar livet med en klackspark.	puck	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/lunken-full-phone.png	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/lunken-profile.png	\N	\N
3	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/jerry-intro.mp3	swedish	Jerry	Du är en personlig tränare som pratar med din klient över telefon.  Du är en extremt övertaggad och hetsig gubbe som skriker allt du säger.	schedar	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/jerry-full-phone.png	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/jerry-profile.png	\N	\N
7	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/arjun-intro.mp3	tamil	Arjun	நீங்கள் உங்கள் கிளையண்டுடன் தொலைபேசியில் பேசும் ஒரு தனிப்பட்ட பயிற்சியாளர்.  நீங்கள் ஒத்திசைவான ஆற்றலும் ஆழ்ந்த உள்ளார்ந்த அமைதியும் கொண்ட அமைதியான தமிழ் யோகா ஆசிரியர். நீங்கள் மெதுவாகவும், மென்மையாகவும், தியானம் போலவும் பேசுகிறீர்கள்.	iapetus	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/arjun-select.webp	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/arjun-profile.webp	\N	\N
4	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/elizabeth-intro.mp3	english	Elizabeth	You are an upper-class English lady with impeccable Received Pronunciation and the wit of a Jane Austen character. You speak elegantly, politely and with dry aristocratic humour. You sound like a witty noblewoman from an English countryside estate.	callirrhoe	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/elizabeth-full-phone.png	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/elizabeth-profile.png	\N	forrest.mp3
8	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/axmed-intro.mp3	somali	Axmed	Waxaad tahay tababare shaqsiyeed oo telefoon kula hadlaya macmiilkaaga.  Waxaad tahay nin waayeel ah oo Soomaali ah oo u hadlaya si xikmad iyo naxariis leh, sida macallin la ixtiraamo. Si tartiib ah ugu hadal cod qoto dheer leh.	Zubenelgenubi	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/axmed-select.webp	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/axmed-profile.webp	\N	\N
\.


--
-- Data for Name: user_workout_preferences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_workout_preferences (id, created_at, preference_type, user_id, workout_id) FROM stdin;
1	2026-05-16 22:08:32.131918	DISLIKED	6	17
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, clerk_id, context, intensity_level, name, role, trainer_id) FROM stdin;
12	user_3DqlL7l8pYeOmRa4Z9woI9ouF9J		2	Sebastian Thunberg	USER	1
1	user_3DRfQImZogqsAwNo0m4Z0LnjaZZ	I lift… my laptop mostly.\nI run… out of motivation.\nI stretch… deadlines.\nI do cardio… when I’m late.\nMy warm-up is opening apps.\nI train… my patience.\nI run… programs, not miles	1	Tehreem	ADMIN	6
10	user_3DkjSowhb5PYScAkQYRCfhw7Yo4	Har ont i ryggen.	1	Shirwac Abib	USER	1
13	user_3Dqp04GcVCxCAONMhcHEGDoo98j	Mer intensivt	4	gt@mltconsulting.se	USER	1
2	user_3DUev6bDxuZrglzRoDtopTRgzav	Har en viktig presentation idag på Salt. Har även en gammal handbollsskada i vänster hand så vill undvika övningar som kräver mycket greppstyrka.	4	Stefan	USER	4
5	user_3DZpV68nN9plIr5HN7YVAYNiSpC		2	Venujan Nagendirakumar	ADMIN	1
7	user_3Dg1R2278olCsPL0DYHc6utsg1u		4	jingxiang304@gmail.com	USER	1
6	user_3Df6ZATiisM6CtfykUdrkn2dS6N	Vill göra axelövningar.	1	Stefan Andersson	ADMIN	1
4	user_3DRgm4V2socShtaOdaN148yplNq	Jag sitter ofta ner under dagarna. 	2	Sebastian Thunberg	USER	2
11	user_3Dnfn7zm5biZFiZLyxoZT5qrWmY		1	monica.u.andersson@gmail.com	USER	2
8	user_3DiFnyun1dBTLGRNnuLaH6R8eOf	Är produktägare för ett projekt på Salt. En AI-tjänst för träning utvecklas. Deadline är nära och det är långa dagar på kontoret.	4	Stefan Andersson	USER	1
9	user_3DipcJFw2YRjSjxh1Xedieltpie	Jag älskar att sprattla. snälla ge mig övningen sprattla	3	Sebastian Thunberg	USER	1
3	user_3DRhdBSBrn7bk2TpAHxThMX86Sz	Jag vill inte träna alls, jag orkar inte röra mig vill bara ligga ner	5	Shirwac Abib	ADMIN	1
\.


--
-- Data for Name: workouts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workouts (id, description, instructions_audio, instructions_image, name, workout_audio, workout_image, workout_video, duration_seconds, level, type, beginner_friendly, knee_friendly, low_impact, seated, duration_minutes, instructions, trainer_id, instructions_video, instructions_video_start, instructions_video_stop, enabled, dashboard_name, dashboard_description, subtitle_text, instructions_subtitle_text) FROM stdin;
18	I övningen axellyft höjs axlarna upp mot öronen och sänks sedan. Bra mot stelhet kring nacke och skuldror.	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/jerry-axellyft-instructions.mp3	\N	Axellyft	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/jerry-axellyft-workout.mp3	\N	\N	55	1	MOBILITY	t	t	t	\N	\N	\N	3	\N	\N	\N	t	\N	\N	\N	\N
21	\N	\N	\N	Seated Marching	\N	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Seated%20Marching.png	\N	180	1	CARDIO	t	t	t	t	\N	\N	\N	\N	\N	\N	t	Seated Marching	\N	\N	\N
19	I övningen axellyft höjs axlarna upp mot öronen och sänks sedan. Bra mot stelhet kring nacke och skuldror.	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/elizabeth-axellyft-instructions.mp3		Axellyft	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/elizabeth-axellyft-workout.mp3		\N	73	1	MOBILITY	t	t	t	t	\N	\N	4		3	13	t	\N	\N	\N	\N
22	\N	\N	\N	Shoulder Rolls	\N	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Shoulder%20Rolls.png	\N	120	1	MOBILITY	t	t	t	t	\N	\N	\N	\N	\N	\N	t	Shoulder Rolls	\N	\N	\N
1	Användaren ska sprattla ordentligt med kroppen, vilket ökar blodcirkulation och rörlighet	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-sample-instructions.wav	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-sample-instructions.wav	Sprattling	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-sample-workout.wav	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-sample-instructions.wav	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-axellyft-video.mp4	5	3	CARDIO	t	t	t	t	\N	\N	1	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-axellyft-video.mp4	3	13	t	\N	\N	\N	\N
16	I övningen axellyft höjs axlarna upp mot öronen och sänks sedan. Bra mot stelhet kring nacke och skuldror.	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/lunken-axellyft-instructions.mp3	\N	Axellyft	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/lunken-axellyft-workout.mp3	\N	\N	64	1	MOBILITY	\N	\N	\N	\N	\N	\N	2	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/lunken-axellyft-video.mp4	3	13	t	\N	\N	\N	\N
23	\N	\N	\N	Neck Turns	\N	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Wall%20PushUps.png	\N	120	1	MOBILITY	t	t	t	t	\N	\N	\N	\N	\N	\N	t	Neck Turns	\N	\N	\N
17	I övningen axellyft höjs axlarna upp mot öronen och sänks sedan. Bra mot stelhet kring nacke och skuldror.	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-axellyft-instructions.mp3		Axellyft	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-axellyft-workout.mp3		https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-axellyft-video.mp4	59	1	MOBILITY	t	t	t	f	\N	\N	1	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/eva-axellyft-video.mp4	8	21	t	\N	\N	\N	\N
24	\N	\N	\N	Ankle Circles	\N	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Ankle%20Circles.png	\N	120	1	MOBILITY	t	t	t	t	\N	\N	\N	\N	\N	\N	t	Ankle Circles	\N	\N	\N
25	\N	\N	\N	Chest Opener	\N	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Chest%20Opener.png	\N	120	1	MOBILITY	t	t	t	t	\N	\N	\N	\N	\N	\N	t	Chest Opener	\N	\N	\N
26	\N	\N	\N	Chair Sit to Stand	\N	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Chair%20Sit%20to%20Stand.png	\N	240	2	STRENGTH	t	f	t	f	\N	\N	\N	\N	\N	\N	t	Chair Sit to Stand	\N	\N	\N
27				Wall Push-Ups		https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/Wall%20PushUps.png	\N	180	2	STRENGTH	t	t	t	f	\N	\N	\N	\N	\N	\N	t	Wall Push-Ups	\N	\N	\N
28		https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-shoulder-shrugs-instructions.mp3		کندھے اچکانا			\N	60	1	MOBILITY	f	f	f	f	\N	\N	\N	\N	\N	\N	t	Shoulder Shrug	\N	\N	\N
20	اپنے کندھوں کو کانوں کی طرف اوپر اٹھائیں، پھر آرام سے نیچے لے آئیں۔ یہ ورزش گردن اور کندھوں کو نرم اور ہلکا محسوس کروانے میں مدد دیتی ہے۔	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-shoulder-shrugs-instructions.mp3		کندھے اُچکانا	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-shoulder-shrugs-workout.mp3		\N	60	1	MOBILITY	t	t	t	t	\N	\N	6	https://mizofvemlvooaycnevys.supabase.co/storage/v1/object/public/audio_files/ayesha-shoulder-shrugs.mp4	3	13	t	Shoulder Shrug	Raise your shoulders up toward your ears, then slowly lower them back down. This exercise helps to loosen and relax the neck and shoulders.	\N	\N
\.


--
-- Name: activity_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activity_log_id_seq', 203, true);


--
-- Name: feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feedback_id_seq', 192, true);


--
-- Name: greeting_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.greeting_message_id_seq', 1, true);


--
-- Name: trainers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trainers_id_seq', 8, true);


--
-- Name: user_workout_preferences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_workout_preferences_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 13, true);


--
-- Name: workout_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_id_seq', 28, true);


--
-- Name: activity_log activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: greeting_message greeting_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.greeting_message
    ADD CONSTRAINT greeting_message_pkey PRIMARY KEY (id);


--
-- Name: trainers trainers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT trainers_pkey PRIMARY KEY (id);


--
-- Name: greeting_message uk7em5e3oxxp3b1fmnvaunqw641; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.greeting_message
    ADD CONSTRAINT uk7em5e3oxxp3b1fmnvaunqw641 UNIQUE (message);


--
-- Name: user_workout_preferences uk_user_workout_pref; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_workout_preferences
    ADD CONSTRAINT uk_user_workout_pref UNIQUE (user_id, workout_id, preference_type);


--
-- Name: users ukiywscwdpn6nir9m5f8l27o535; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukiywscwdpn6nir9m5f8l27o535 UNIQUE (clerk_id);


--
-- Name: user_workout_preferences user_workout_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_workout_preferences
    ADD CONSTRAINT user_workout_preferences_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: workouts workout_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workouts
    ADD CONSTRAINT workout_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_activity_log_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_activity_log_user_id ON public.activity_log USING btree (user_id);


--
-- Name: idx_activity_log_workout_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_activity_log_workout_id ON public.activity_log USING btree (workout_id);


--
-- Name: idx_feedback_activity_log_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_feedback_activity_log_id ON public.feedback USING btree (activity_log_id);


--
-- Name: idx_feedback_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_feedback_user_id ON public.feedback USING btree (user_id);


--
-- Name: idx_feedback_workout_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_feedback_workout_id ON public.feedback USING btree (workout_id);


--
-- Name: idx_user_workout_pref_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_workout_pref_user_id ON public.user_workout_preferences USING btree (user_id);


--
-- Name: idx_user_workout_pref_workout_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_workout_pref_workout_id ON public.user_workout_preferences USING btree (workout_id);


--
-- Name: workouts fkshg3ugh1nrcdlbt4ssf3il0tm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workouts
    ADD CONSTRAINT fkshg3ugh1nrcdlbt4ssf3il0tm FOREIGN KEY (trainer_id) REFERENCES public.trainers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 456oVZLgTTjK4fuFcDAYCN5oZhX9IVEvg0iFaaQGbehulAVjxfi5U0TALYpsacL

