/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiDevRouteImport } from './routes/ai-dev'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionWorkoutIdRouteImport } from './routes/session.$workoutId'

const AiDevRoute = AiDevRouteImport.update({
  id: '/ai-dev',
  path: '/ai-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionWorkoutIdRoute = SessionWorkoutIdRouteImport.update({
  id: '/session/$workoutId',
  path: '/session/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-dev': typeof AiDevRoute
  '/session/$workoutId': typeof SessionWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-dev': typeof AiDevRoute
  '/session/$workoutId': typeof SessionWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-dev': typeof AiDevRoute
  '/session/$workoutId': typeof SessionWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/ai-dev' | '/session/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/ai-dev' | '/session/$workoutId'
  id: '__root__' | '/' | '/admin' | '/ai-dev' | '/session/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiDevRoute: typeof AiDevRoute
  SessionWorkoutIdRoute: typeof SessionWorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-dev': {
      id: '/ai-dev'
      path: '/ai-dev'
      fullPath: '/ai-dev'
      preLoaderRoute: typeof AiDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$workoutId': {
      id: '/session/$workoutId'
      path: '/session/$workoutId'
      fullPath: '/session/$workoutId'
      preLoaderRoute: typeof SessionWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiDevRoute: AiDevRoute,
  SessionWorkoutIdRoute: SessionWorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
